# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Quality

on:
  push:
  pull_request:
    branches: [ "main" ]

jobs:
  # Label of the container job
  setup-node-pnpm:
    uses: ./.github/workflows/install_node_pnpm.yaml

  quality:
    runs-on: ubuntu-latest
    needs: setup-node-pnpm
    name: Format Check Prettier
    steps:
      # Downloads a copy of the code in your repository before running CI tests
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install dev dependencies
        run: pnpm install --dev

      - name: Run Format Check Script
        run: pnpm run format:check


